name: Run Tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Add PWD to pythonpath
        run: |
          echo 'PYTHONPATH<<EOF' >> $GITHUB_ENV
          echo $(pwd) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run tests
        run: |
          pytest .